### PR TITLE
Added Secrets of JS Ninja by John Resig and Pro JS for Web Devs by Nick Zakas

### PR DESCRIPTION
**Pull request by CollinGraves**
Added Secrets of JS Ninja by John Resig and Pro JS for Web Developers by Nicholas Zakas. Both of these books gave me a firm footing when I started learning more advanced JS two years ago.

### CODE REVIEW

**Comment by kimjoar** [comment]
@CollinGraves Thanks for the links. And sorry for the laaate response. We've had a bit of break.

Sadly I haven't read any of these yet. We try to keep the overlap between resources as small as possible, and from what I can see (let me know if I misjudged them based on their TOC) they appear to overlap quite a bit, both with each other and with http://eloquentjavascript.net/, which is already included as a resource.

A huge point in favour of Eloquent JavaScript is that's freely available online, so I think for now we lean towards keeping it as our primary "learn lots of js from a book" type of resource.

Let's see what some of the others on the team think: @mikaelbr @mollerse @mobmad Any thoughts?

**Comment by mikaelbr** [comment]
I'm sorry to say I haven't read them either, but I think you make a very good point with the freely available  resources. I think the key strategy here should be to provide good, solid resources and if possible having them available free and momentarily.

**Comment by CollinGraves** [comment]
Kim,

Thanks for the response! This was so long ago, I'll have to go back and
remind myself of the resources I recommended. I'll dig back in to the ol'
knowledge repository and see if anything else looks shiny (and free).
Thanks for the additional feedback, Mikael!

**Comment by mollerse** [comment]
Also have not read either of these two books, so my thoughts are based on the ToCs. As we already have two resources (JS Apps - Maccaw and Eloquent JS - Haverbeke) that cover most of the same points as these two some further comparison would be needed. Books are an expensive, time-wise, investment and we should be sure that a certain book is worth the time it takes to read it.

**Professional JavaScript for Web Developers**

It looks very extensive, clocking in at over 600 pages. Judging by the ToC it does attempt to cover just about everything you would need, and I'm having doubts about wether that content will still be up to date. Adding such an extensive resource is risky with the JavaScript world moving so fast. It also seems more geared towards developers who already have a background in more enterprisy environments.

**Secrets of the JavaScript Ninja**

Seems to cover pretty much the same as Eloquent JavaScript. With Eloquent being free and more recent, I'm doubtful that Secrets of the JavaScript Ninja will be worth replacing it with.

**Comment by mikaelbr** [comment]
I guess we are keeping Eloquent JavaScript in favour of these additions and closing this PR, @kjbekkelund and @mollerse ?

**Comment by mollerse** [comment]
LGTM

**Pull request closed without merging**
