### PR TITLE
add new guide performance

### PR DESCRIPTION
**Pull request by keppelen**

### CODE REVIEW

**Comment by kimjoar** [comment]
Hi Giovanni! Thanks for the suggestion. This looks great. I'll have to sit down in a couple of days to take a better look at it and see if it fits the rest of the content on the site :)

**Comment by keppelen** [comment]
thank you @kjbekkelund :)

**Comment by kimjoar** [comment]
This is a great resource, but also some strange micro-optimization stuff that I'm not a big fan of. I don't think I ever have profiled an app and found the use of `$.each` to be a bottleneck. Also, it leads people to think that `$.map`, `$.filter` and other really great functional stuff is slow. [jsperf](http://jsperf.com/browser-diet-dom-manipulation/6) based on [this](http://browserdiet.com/#dont-touch-dom) example.

Also, never been a fan of the "store the size of the array that will be covered" stuff. These are things to think about in a really hot code path, but for normal apps? As said, never experienced it to be a problem. How you work with the DOM, how you bind events, how you clean up memory, and so on are far more important.

That said, there's a lot of really good stuff in there and we might be pulling this in, I just have to check out some other resources to get a feel for what's out there — It's been a long time since I last checked.

**Comment by keppelen** [comment]
OK :)

**Comment by Ore4444** [comment]
+1

Although much of it is too technical and doesn't really explain the reasoning behind the procedures, it is quite comprehensive

**Comment by keppelen** [comment]
cc @zenorocha

**Comment by zenorocha** [comment]
+1

**Pull request closed without merging**
