### PR TITLE
Add two posts: "The Hikikomori's Guide to JavaScript" and "How do Promises Work?"

### PR DESCRIPTION
**Pull request by ythecombinator**
This *PR* basically adds two very useful posts from @robotlolita.

- [**The Hikikomori's Guide to JavaScript**](http://robotlolita.me/2013/04/27/the-hikikomoris-guide-to-javascript.html): This post provides a few hints on best practices when thinking about applications architecture, leading us to achieve **small**, **composable** and **extensible** applications. The post is very well written; explaining succinctly the important steps when it comes to the organization of a JavaScript application - which goes much beyond, since the covered principles are actually *language-agnostic* - and it also has several examples of code.

- [How do Promises Work?](http://robotlolita.me/2015/11/15/how-do-promises-work.html): The same as above but now the covered topics are *promises*. It gives us a bunch of knowledge over this topic, which involves *handling errors*, *combining promises*, a lot of theory behind them, practical examples - and it all comes very well illustrated!

### CODE REVIEW

**Comment by mikaelbr** [comment]
I like it! 👍 Could you just remove the added whitespace also?

**Comment by ythecombinator** [comment]
Oh, my bad @mikaelbr. I'll do it now 😄

**Comment by mikaelbr** [comment]
Great!

**Comment by ythecombinator** [comment]
Is that okay now?

**Comment by mikaelbr** [comment]
Indeed it is. Thanks for the pr and contribution! 🍰

**Comment by ythecombinator** [comment]
And I thank you all for the great initiative! 🎆

**Comment by anoop-gupt** [comment]
Thanks all! Good initiative.

**Pull request merged**
