### PR TITLE
Use free Code School course instead of slides on debugging

### PR DESCRIPTION
**Pull request by kimjoar**
The current resource touches on more topics, but I think this is a far better walkthrough of the developer tools. It's also great that this is a free course. I would really like to have a good introduction to the DevTools before we link directly to the documentation, even though the documentation is very good. /cc @olav @mobmad

### CODE REVIEW

**Comment by kimjoar** [comment]
This is also a great 4min video by Remy Sharp on working directly in the DevTools: http://www.youtube.com/watch?v=ura4ee4fjZs and http://remysharp.com/2012/12/21/my-workflow-never-having-to-leave-devtools/

Might be a little short, but it's an interesting idea.

**Comment by kimjoar** [comment]
Thoughts @mobmad @olav ?

**Comment by olav** [comment]
Yes, +1.

Seems like Code School has a lot more interesting content than the presentation.

I think we should add the blog post by Remy Sharp, but not the YouTube link, as the blog post also links to the video.

**Comment by kimjoar** [comment]
Agreed, the blog post is better than only the YouTube link.

**Comment by mobmad** [comment]
+1 on Code School - a high quality interactive course

As for the blog post/video, I think its too narrow in this context.

**Comment by kimjoar** [comment]
@mobmad Good point. I agree on the video. Should I just pull in the course and update the Twitter account? :)

**Comment by kimjoar** [comment]
Merged. Let's update Twitter tomorrow.

**Pull request merged**
