### PR TITLE
Add section on security

### PR DESCRIPTION
**Pull request by kimjoar**
We should have something on security. And it just didn't fit anywhere else. We'll have to gradually build it out.

We need something for the additional text in the ToC, any ideas?

(btw, I tagged 1.0, so it's easier to diff all the new stuff when we're sending the email newsletters)

### CODE REVIEW

**Comment by kimjoar** [comment]
@olav I'm in favor of publishing and keep working on finding more and better resources. This is not much, but I feel it's better than nothing. Do have any ideas for ToC description?

**Comment by kimjoar** [comment]
I think I found one. To secs, going to update the PR.

**Comment by kimjoar** [comment]
Now we have 3 :) Just need a ToC text.

**Comment by kimjoar** [comment]
"Don't get hacked"
"Keep the hackers away"
?

**Comment by olav** [comment]
The ToC-text should reflect the content of the articles. Something like:

Securing your app: Principles, access control, validation and tokens

**Comment by kimjoar** [comment]
Great point. Fixed and merged.

**Pull request merged**
