### PR TITLE
Adds initial contributing guidelines

### PR DESCRIPTION
**Pull request by mikaelbr**
To open a discussion of the contents of CONTRIBUTING.md

### CODE REVIEW

**Comment by kimjoar** [comment]
@mikaelbr Great start!

@mollerse Great ideas in #51. Contributions other than resources are indeed valuable, and we should mention it in the doc. I also like the idea about requests for resources. What's the easiest way for someone else to extend a pull request?

Are there any CoCs that are easily linkable or used as a basis? (E.g. something like "we expect everyone to follow ...")

**Comment by mollerse** [comment]
Just like a contributing.md-file I think there is value in having a conduct.md in our own repo. Maintaining our own CoC lets us be specific about our use case. I don't think CoCs are at the point where it becomes as standardised as a liscence.md.

As i mentioned in #51 there are a couple of great starting points which we can tailor to fit our need.

**Comment by kimjoar** [comment]
@mollerse Agreed. Want to create an initial version?

**Comment by kimjoar** [comment]
@mikaelbr Maybe we should move all the "topics we're interested in" to Github issues labeled "request"? Easier to discuss the specific topic and suggest resources there.

**Comment by mikaelbr** [comment]
@kjbekkelund Yep. I'll make the move.

**Comment by mikaelbr** [comment]
We now have the `request` label, and a list of resources we are interested in for the time being: https://github.com/superherojs/superherojs/labels/request

The advantage of having this as issues are that we can have open discussions and it's a much more moving/living list.

**Comment by kimjoar** [comment]
Great stuff! @mobmad @olav Any changes you want incorporated? Otherwise I'll go ahead and merge this.

**Comment by kimjoar** [comment]
@mikaelbr I tried to incorporate a little bit more about why into the vision. Does it look ok?

**Comment by mikaelbr** [comment]
Looks good! Maybe general instead of generic?

**Pull request merged**
